import { chromium } from 'playwright';
import { pathToFileURL } from 'url';
import path from 'path';
const html = path.resolve('recording/medium_cover.html');
const out = `${process.env.HOME}/Downloads/Understudy-Medium-Cover.png`;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1200, height: 630 }, deviceScaleFactor: 2 });
await page.goto(pathToFileURL(html).href, { waitUntil: 'networkidle' });
await page.waitForTimeout(200);
await page.screenshot({ path: out, clip: { x: 0, y: 0, width: 1200, height: 630 } });
await browser.close();
console.log('WROTE', out);
