#!/usr/bin/env python3
"""Google Workspace Real Delivery Test Script.

When `understudy_agent/token.json` is present and `GOOGLE_WORKSPACE_ENABLED=true`,
creates a real Gmail draft, a real Calendar event, and a real Google Doc,
printing their working URLs.

Skips gracefully with a clear message if `token.json` is missing or disabled.
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Ensure root workspace is on path
ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

# Load environment
env_file = ROOT_DIR / "understudy_agent" / ".env"
load_dotenv(dotenv_path=env_file)
load_dotenv()

TOKEN_FILE = ROOT_DIR / "understudy_agent" / "token.json"

def test_google_delivery():
    print("=" * 70)
    print("🚀 Google Workspace Delivery Acceptance Test")
    print("=" * 70)

    # 1. Check if token file exists
    if not TOKEN_FILE.exists() and not (ROOT_DIR / "token.json").exists():
        print("ℹ️  [SKIP] 'understudy_agent/token.json' not found.")
        print("   To run real delivery against your Google account:")
        print("   1. Place your OAuth client secret in 'understudy_agent/client_secret.json'.")
        print("   2. Run: python scripts/google_auth.py")
        print("   3. Run: GOOGLE_WORKSPACE_ENABLED=true python scripts/test_google_delivery.py")
        print("=" * 70)
        sys.exit(0)

    # 2. Check if GOOGLE_WORKSPACE_ENABLED is set
    enabled_str = os.getenv("GOOGLE_WORKSPACE_ENABLED", "").lower()
    if enabled_str not in ("1", "true", "yes"):
        print("ℹ️  [SKIP] GOOGLE_WORKSPACE_ENABLED is not set to 'true'.")
        print("   To test real Google Workspace delivery, run:")
        print("   GOOGLE_WORKSPACE_ENABLED=true python scripts/test_google_delivery.py")
        print("=" * 70)
        sys.exit(0)

    from understudy_agent import google_delivery

    print(f"Token file found: {TOKEN_FILE}")
    print(f"GOOGLE_WORKSPACE_ENABLED: {os.getenv('GOOGLE_WORKSPACE_ENABLED')}")
    print("\nExecuting live Google Workspace API calls...")

    # 3. Create Gmail Draft
    print("\n[1/3] Testing Gmail Draft Creation (create_gmail_draft)...")
    try:
        draft_res = google_delivery.create_gmail_draft(
            to="team@example.com",
            subject="[Understudy] Quarterly Strategic Review & Milestones",
            body=(
                "Hi Team,\n\n"
                "This is an automated draft generated by Understudy during the Monday Product Sync.\n"
                "Please review the proposed milestones before sending.\n\n"
                "Best,\nUnderstudy Agent"
            ),
        )
        print("  ✅ Gmail draft created successfully!")
        print(f"     Draft ID:  {draft_res.get('draftId')}")
        print(f"     Draft URL: {draft_res.get('url')}")
    except Exception as e:
        print(f"  ❌ Failed to create Gmail draft: {e}")
        raise

    # 4. Create Calendar Event
    print("\n[2/3] Testing Google Calendar Event Creation (create_calendar_event)...")
    try:
        start_iso = google_delivery.parse_proposed_time_to_iso("Thursday at 2:00 PM")
        cal_res = google_delivery.create_calendar_event(
            title="Understudy Cross-Functional Design Review",
            start_iso=start_iso,
            attendees=["alex@example.com", "sam@example.com"],
            description="Tentative hold scheduled automatically by Understudy Agent.",
        )
        print("  ✅ Calendar event created successfully!")
        print(f"     Event ID:     {cal_res.get('eventId')}")
        print(f"     Calendar URL: {cal_res.get('htmlLink')}")
    except Exception as e:
        print(f"  ❌ Failed to create Calendar event: {e}")
        raise

    # 5. Create Google Doc
    print("\n[3/3] Testing Google Doc Creation (create_google_doc)...")
    try:
        doc_content = (
            "Understudy Product Specification\n\n"
            "1. Overview\n"
            "Autonomous meeting assistant delivering real-time action item execution.\n\n"
            "2. Delivery Integrations\n"
            "- Gmail draft & send\n"
            "- Google Calendar event scheduling\n"
            "- Google Docs generation\n"
        )
        doc_res = google_delivery.create_google_doc(
            title="Understudy - Checkout Endpoints API Spec",
            content=doc_content,
        )
        print("  ✅ Google Doc created successfully!")
        print(f"     Doc ID:   {doc_res.get('docId')}")
        print(f"     Doc URL:  {doc_res.get('url')}")
    except Exception as e:
        print(f"  ❌ Failed to create Google Doc: {e}")
        raise

    print("\n" + "=" * 70)
    print("🎉 ALL GOOGLE WORKSPACE DELIVERIES SUCCEEDED WITH WORKING URLS!")
    print(f"📧 Gmail Draft:  {draft_res.get('url')}")
    print(f"📅 Calendar:     {cal_res.get('htmlLink')}")
    print(f"📄 Google Doc:   {doc_res.get('url')}")
    print("=" * 70)

if __name__ == "__main__":
    test_google_delivery()
